import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  // GENERAL///
  dashboardContainer: { flex: 1, backgroundColor: '#f8f9fa' },
  input: { backgroundColor: '#fff', paddingVertical: 14, paddingHorizontal: 16, borderRadius: 10, fontSize: 15, color: '#2d3748', marginBottom: 14, borderWidth: 1, borderColor: '#e2e8f0' },

  // NAVBAR//
  navBar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 18, paddingVertical: 14, backgroundColor: '#fff', shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.06, shadowRadius: 6, elevation: 4 },
  navLogo: { fontSize: 22, fontWeight: '800', color: '#2b6cb0', letterSpacing: -0.5 },
  navActions: { flexDirection: 'row', alignItems: 'center' },
  navBtnAdmin: { backgroundColor: '#feebc8', paddingHorizontal: 12, paddingVertical: 7, borderRadius: 20 },
  navBtnAdminText: { color: '#c05621', fontWeight: '700', fontSize: 12 },
  navBtn: { backgroundColor: '#f7fafc', width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#e2e8f0' },
  navBtnText: { fontSize: 16 },
  navBtnLogout: { backgroundColor: '#fed7d7', width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  navBtnLogoutText: { color: '#c53030', fontWeight: '800', fontSize: 14 },

  // FILTER BAR//
  filterBar: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 10, backgroundColor: '#fff', borderBottomWidth: 1, borderColor: '#edf2f7' },
  filterSearchInput: { flex: 1, backgroundColor: '#f7fafc', borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 10, paddingHorizontal: 14, paddingVertical: 9, fontSize: 14, color: '#2d3748', marginRight: 10 },
  filterMenuBtn: { paddingHorizontal: 14, paddingVertical: 9, borderRadius: 10, backgroundColor: '#f7fafc', borderWidth: 1, borderColor: '#e2e8f0' },
  filterMenuBtnActive: { backgroundColor: '#2b6cb0', borderColor: '#2b6cb0' },
  filterMenuBtnText: { fontWeight: '700', fontSize: 13, color: '#4a5568' },
  filterDropdown: { backgroundColor: '#fff', marginHorizontal: 16, marginTop: 6, borderRadius: 14, padding: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.08, shadowRadius: 12, elevation: 5, borderWidth: 1, borderColor: '#edf2f7' },
  filterLabel: { fontSize: 12, fontWeight: '700', color: '#718096', textTransform: 'uppercase', marginBottom: 8, letterSpacing: 0.5 },
  filterInput: { backgroundColor: '#f7fafc', borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8, fontSize: 14, color: '#2d3748' },
  filterChip: { paddingHorizontal: 14, paddingVertical: 7, borderRadius: 20, backgroundColor: '#f7fafc', borderWidth: 1, borderColor: '#e2e8f0', marginRight: 8 },
  filterChipActive: { backgroundColor: '#2b6cb0', borderColor: '#2b6cb0' },
  filterChipText: { fontSize: 13, fontWeight: '600', color: '#4a5568' },
  filterResetBtn: { backgroundColor: '#fff5f5', borderWidth: 1, borderColor: '#fed7d7', borderRadius: 10, paddingVertical: 10, alignItems: 'center' },
  filterResetBtnText: { color: '#c53030', fontWeight: '700', fontSize: 13 },

  // CAR CARDS//
  carCard: { backgroundColor: '#fff', borderRadius: 20, marginBottom: 20, overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.08, shadowRadius: 12, elevation: 5 },
  carImage: { width: '100%', height: 180, resizeMode: 'cover' },
  availabilityOverlay: { position: 'absolute', top: 12, left: 12, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20 },
  availabilityOverlayText: { color: '#fff', fontSize: 11, fontWeight: 'bold' },
  priceOverlay: { position: 'absolute', bottom: 12, right: 12, backgroundColor: 'rgba(0,0,0,0.65)', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 12, flexDirection: 'row', alignItems: 'baseline' },
  priceOverlayText: { color: '#fff', fontWeight: '800', fontSize: 18 },
  priceOverlaySuffix: { color: 'rgba(255,255,255,0.75)', fontSize: 11, marginLeft: 3 },
  carCardBody: { padding: 14 },
  carCardName: { fontSize: 18, fontWeight: '800', color: '#1a202c', marginBottom: 10 },
  carCardTags: { flexDirection: 'row' },
  carTag: { backgroundColor: '#f7fafc', borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 5, marginRight: 8 },
  carTagText: { fontSize: 12, color: '#4a5568', fontWeight: '600' },
  deleteBtn: { marginHorizontal: 16, marginBottom: 14, paddingVertical: 9, borderRadius: 10, backgroundColor: '#fff5f5', borderWidth: 1, borderColor: '#fed7d7', alignItems: 'center' },
  deleteBtnText: { color: '#c53030', fontWeight: '600', fontSize: 13 },

  // DETAILS//
  backButton: { padding: 14, backgroundColor: '#fff' },
  backButtonText: { color: '#2b6cb0', fontWeight: 'bold' },
  detailsHeroImage: { width: '100%', height: 220 },
  detailsTitle: { fontSize: 24, fontWeight: 'bold' },
  detailsSub: { fontSize: 14, color: '#718096' },
  quoteWrapper: { marginTop: 15, padding: 14, backgroundColor: '#fff', borderRadius: 8, borderWidth: 1, borderColor: '#edf2f7' },
  quoteTitle: { fontSize: 14, fontWeight: 'bold', marginBottom: 6 },
  quoteLine: { flexDirection: 'row', justifyContent: 'space-between', marginVertical: 4 },
  quoteLabel: { color: '#718096' },
  quoteValue: { fontWeight: '500' },
  finalGrandPrice: { fontSize: 20, fontWeight: 'bold', color: '#2b6cb0' },
  bookActionBtn: { backgroundColor: '#48bb78', paddingVertical: 14, borderRadius: 10, alignItems: 'center', marginTop: 15 },
  bookActionBtnText: { color: '#fff', fontWeight: 'bold', fontSize: 15 },

  // HISTORY//
  historyHeader: { backgroundColor: '#fff', paddingHorizontal: 16, paddingVertical: 14, borderBottomWidth: 1, borderColor: '#edf2f7' },
  historyTitle: { fontSize: 22, fontWeight: '800', color: '#1a202c', marginTop: 4 },
  historyCount: { fontSize: 13, color: '#718096', marginTop: 2 },
  historyEmpty: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 40 },
  historyEmptyTitle: { fontSize: 20, fontWeight: '700', color: '#2d3748', marginTop: 16 },
  historyEmptyText: { fontSize: 14, color: '#718096', textAlign: 'center', marginTop: 8 },
  historyEmptyBtn: { marginTop: 20, backgroundColor: '#2b6cb0', paddingHorizontal: 24, paddingVertical: 12, borderRadius: 12 },
  historyEmptyBtnText: { color: '#fff', fontWeight: '700', fontSize: 14 },
  historyCardNew: { backgroundColor: '#fff', borderRadius: 20, marginBottom: 16, overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.07, shadowRadius: 10, elevation: 4 },
  historyCardImage: { width: '100%', height: 150, resizeMode: 'cover' },
  historyStatusBadge: { position: 'absolute', top: 12, right: 12, paddingHorizontal: 12, paddingVertical: 5, borderRadius: 20, borderWidth: 1 },
  historyStatusText: { fontSize: 12, fontWeight: '700' },
  historyCardContent2: { padding: 16 },
  historyCarName2: { fontSize: 18, fontWeight: '800', color: '#1a202c', marginBottom: 10 },
  historyInfoRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 5 },
  historyInfoIcon: { fontSize: 13, marginRight: 8 },
  historyInfoText: { fontSize: 13, color: '#4a5568' },
  historyCardFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 14, paddingTop: 14, borderTopWidth: 1, borderColor: '#edf2f7' },
  historyPriceNew: { fontSize: 22, fontWeight: '800', color: '#2b6cb0' },
  cancelBtn: { backgroundColor: '#fff5f5', borderWidth: 1, borderColor: '#fed7d7', paddingHorizontal: 16, paddingVertical: 8, borderRadius: 10 },
  cancelBtnText: { color: '#c53030', fontWeight: '700', fontSize: 13 },

  // ADMIN//
  sectionTitle: { fontSize: 20, fontWeight: 'bold', color: '#2d3748', marginBottom: 4 },
  sectionSubtitle: { fontSize: 13, color: '#718096', marginBottom: 15 },
  calendarMiniLabel: { fontSize: 11, color: '#718096', fontWeight: '600', textTransform: 'uppercase', marginBottom: 4 },
  cityChip: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 10, backgroundColor: '#fff', marginRight: 6, borderWidth: 1, borderColor: '#e2e8f0', alignSelf: 'center' },
  activeCityChip: { backgroundColor: '#2b6cb0', borderColor: '#2b6cb0' },
  pickerTriggerSurface: { backgroundColor: '#edf2f7', borderWidth: 2, borderColor: '#cbd5e0', borderStyle: 'dashed', borderRadius: 10, paddingVertical: 24, alignItems: 'center', justifyContent: 'center', marginVertical: 12 },
  pickerPreviewContainer: { position: 'relative', marginVertical: 12, borderRadius: 10, overflow: 'hidden', borderWidth: 1, borderColor: '#e2e8f0' },
  pickerPreviewImage: { width: '100%', height: 180, resizeMode: 'cover' },
  pickerResetBadge: { position: 'absolute', top: 10, right: 10, backgroundColor: 'rgba(0,0,0,0.65)', paddingVertical: 6, paddingHorizontal: 12, borderRadius: 15 },

  // PROFILE//
  profileAvatarSection: { alignItems: 'center', marginBottom: 24 },
  profileAvatar: { width: 100, height: 100, borderRadius: 50, borderWidth: 3, borderColor: '#2b6cb0' },
  profileAvatarPlaceholder: { width: 100, height: 100, borderRadius: 50, backgroundColor: '#edf2f7', alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#e2e8f0' },
  profileAvatarBadge: { position: 'absolute', bottom: 0, right: 0, backgroundColor: '#2b6cb0', width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#fff' },
  profileName: { fontSize: 22, fontWeight: '800', color: '#1a202c', marginTop: 12 },
  profileEmail: { fontSize: 13, color: '#718096', marginTop: 4 },
  profileAdminBadge: { backgroundColor: '#feebc8', paddingHorizontal: 14, paddingVertical: 5, borderRadius: 20, marginTop: 8 },
  profileAdminBadgeText: { color: '#c05621', fontWeight: '700', fontSize: 12 },
  profileCard: { backgroundColor: '#fff', borderRadius: 16, padding: 18, marginBottom: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.06, shadowRadius: 8, elevation: 3 },
  profileCardTitle: { fontSize: 15, fontWeight: '700', color: '#2d3748', marginBottom: 16 },
  profileStatsRow: { flexDirection: 'row', marginBottom: 20 },
  profileStatBox: { flex: 1, backgroundColor: '#fff', borderRadius: 12, padding: 14, alignItems: 'center', marginHorizontal: 4, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 4, elevation: 2 },
  profileStatNumber: { fontSize: 18, fontWeight: '800', color: '#2b6cb0' },
  profileStatLabel: { fontSize: 11, color: '#718096', marginTop: 4, textAlign: 'center' },
});
export default styles;